### PR TITLE
some changes for 0.7.2

### PR DESCRIPTION
**Pull request by davidB**
Hi,

To work with our projects, I have to update .classpath with
- jar for compile/test/runtime (to be able to make Run As...)
- resources

I includes some changes made by others
They need to cleanup and refactor but it works.

/davidB

### CODE REVIEW

**Comment by musk** [comment]
Hi davidB,

I pulled down your stuff and I have a question about your classpath method. 
In what situation is the project a UnmanagedClasspathProject?

I'm not sure that adding the runtime jars to your compile classpath in eclipse is the correct solution. This might cause conflicts during compilation for other types of projects. 
I will see how eclipse specifies the runtime path in order to make them only available to the "Run as" method.

**Comment by davidB** [comment]
Hi,

In some of the project I work, there is a jar put under lib dir => available via UnmanagedClasspathProject

Eclipse only have one classpath (Build Path), share for every scope (by default) : compile, test, runtime.
"Run As ..." launcher then allow to override and customize the classpath but it's not part of .classpath or .project
It's the same issue for "test" scope.

Note : i 'm new to sbt (and in the company project), and I only want to be able to use eclipse with the multi-module project and some singe project (lift) I work on.

**Comment by davidB** [comment]
Oups,

I don't know when a project is only a  UnmanagedClasspathProject, but it's possible (allowed by api), and providing a default   (correct ?) behavior is better than returning Nil (IMHO).

**Comment by musk** [comment]
You are probably right. I will need some more time to make tests and then I will merge the changes into my current 0.8.0 branch

**Comment by davidB** [comment]
If you need some change in the scala eclipse plugin (scalaIDE), you can ask me or open a ticket and assign to me (David Bernard)

**Comment by peewhy** [comment]
Hi,

I do not know if this is related to my problem: Adding  scala-compiler to teh dependency list (val scalaCompiler = "org.scala-lang" % "scala-compiler" % "2.8.1" % "test->default") will not add the corresponding jar to the dependencies. Thus, MainGenericRunner can't be used in code (for LiftConsole). The only workaround I found was to update the .classpath file by hand. Does your patch address this ?

**Comment by davidB** [comment]
No it doesn't fix this issue (I did a quick try).
IIRC SBT as special behavior for scala-libary and scala-compiler

**Comment by musk** [comment]
@peewhy: Could you add this as a new issue and if possible provide a simple test project. I think the compiler has to be added as a further customization parameter (like is done with scala-library and sbt-library) in order to get it onto the classpath

**Comment by davidB** [comment]
May I'll request an other push later to support "withSources".

(I really dislike the way SBT 0.7.x manage dependency (vs Maven), it cause me lot of trouble at works)

**Comment by musk** [comment]
I just pushed 0.8.0 branch with your changes and my changes merged. If possible could you test it

**Comment by davidB** [comment]
Thanks, I'll try it.

**Comment by davidB** [comment]
Currently, I didn' seen "broken" behavior.
I had to change the version of eclipsify in Plugins.scala because I didn't have 0.7.1-SNAPSHOT.

Can you deploy 0.8.0, then I'll try tried it at work (bigger projects)

**Comment by musk** [comment]
I'll see if I'm able to push a 0.8.0-SNAPSHOT release to scala-tools.
But it can take til the weekend until I'm ready to do so.
- Stefan

2011/5/10 davidB
reply@reply.github.com:

**Comment by davidB** [comment]
Don't worry, I publish in my company as 0.8.0-pre20110509. (we can't upload 3rd party SNAPSHOT).
What is your plan about Stephan's pull request ?

Thanks for your's plugin.

I've got an issue with our multi-project due to way SBT/eclipse manage relation between project.
Should we link the jar or the target/.../classes in the classpath :
- for direct sibbling modules
- for transitive sibbling modules

Any Idea ?

**Comment by musk** [comment]
2011/5/10 davidB
reply@reply.github.com:

> Don't worry, I publish in my company as 0.8.0-pre20110509. (we can't upload 3rd party SNAPSHOT).
> What is your plan about Stephan's pull request ?
> I have it set up in my local git repository but I didn't find any time
> yet to actually integrate it. I wanted to get the 0.8.0 branch out
> first.
> 
> Thanks for your's plugin.
> 
> I've got an issue with our multi-project due to way SBT/eclipse manage relation between project.
> Should we link the jar or the target/.../classes in the classpath :
> - for direct sibbling modules
> - for transitive sibbling modules
> 
> Any Idea ?
> Ideally the projects should be linked using the target classes
> attributes when building for projects and subprojects and use the jars
> when building a subproject standalone. Analog to how mavens
> eclipse:eclipse task works.
> I'm not sure if this distinction is actually possible in SBT 0.7.x.

**Pull request closed without merging**
